//
// Created by tricc on 2023/10/12.
//

#ifndef KEYKG_HUBLABELGENERATOR_HUBLABELGENERATORABSTRACT_HUBLABELGENERATORABSTRACT_H_
#define KEYKG_HUBLABELGENERATOR_HUBLABELGENERATORABSTRACT_HUBLABELGENERATORABSTRACT_H_

class AbstractHLGenerator{
 public:
  virtual void gen_hub_label_file(const char* dstPath,const char *wgFilePath)=0;
};
#endif //KEYKG_HUBLABELGENERATOR_HUBLABELGENERATORABSTRACT_HUBLABELGENERATORABSTRACT_H_
